//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Respository.Sons
{
    using System;
    public partial class FNews:BaseRespository<EF.Entitys.FNews>,EF.IRespository.Sons.IFNews
    {
    
    }
    public partial class FAI:BaseRespository<EF.Entitys.FAI>,EF.IRespository.Sons.IFAI
    {
    
    }
    public partial class FDataMaterial:BaseRespository<EF.Entitys.FDataMaterial>,EF.IRespository.Sons.IFDataMaterial
    {
    
    }
    public partial class FDataRepository:BaseRespository<EF.Entitys.FDataRepository>,EF.IRespository.Sons.IFDataRepository
    {
    
    }
    public partial class FPayGood:BaseRespository<EF.Entitys.FPayGood>,EF.IRespository.Sons.IFPayGood
    {
    
    }
    public partial class FPayMert:BaseRespository<EF.Entitys.FPayMert>,EF.IRespository.Sons.IFPayMert
    {
    
    }
    public partial class FPayOrder:BaseRespository<EF.Entitys.FPayOrder>,EF.IRespository.Sons.IFPayOrder
    {
    
    }
    public partial class FSys_Config:BaseRespository<EF.Entitys.FSys_Config>,EF.IRespository.Sons.IFSys_Config
    {
    
    }
    public partial class FPayWay:BaseRespository<EF.Entitys.FPayWay>,EF.IRespository.Sons.IFPayWay
    {
    
    }
    public partial class FSys_LoginSession:BaseRespository<EF.Entitys.FSys_LoginSession>,EF.IRespository.Sons.IFSys_LoginSession
    {
    
    }
    public partial class FSys_Role:BaseRespository<EF.Entitys.FSys_Role>,EF.IRespository.Sons.IFSys_Role
    {
    
    }
    public partial class FSysUser:BaseRespository<EF.Entitys.FSysUser>,EF.IRespository.Sons.IFSysUser
    {
    
    }
    
    
    
}
