//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Respository.Sons
{
    using System;
    public partial class FNews:BaseRespository<EF.Entitys.FNews>,EF.IRespository.Sons.IFNews
    {
    
    }
    public partial class FRepository:BaseRespository<EF.Entitys.FRepository>,EF.IRespository.Sons.IFRepository
    {
    
    }
    public partial class InRawMaterial:BaseRespository<EF.Entitys.InRawMaterial>,EF.IRespository.Sons.IInRawMaterial
    {
    
    }
    
    
    
}
