//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IService.Sons
{
    using System;
    
    public partial interface IFDataMaterial:IBaseService<EF.Entitys.FDataMaterial>
    {
    
    }
    public partial interface IFNews:IBaseService<EF.Entitys.FNews>
    {
    
    }
    public partial interface IFPayGood:IBaseService<EF.Entitys.FPayGood>
    {
    
    }
    public partial interface IFPayMert:IBaseService<EF.Entitys.FPayMert>
    {
    
    }
    public partial interface IFPayOrder:IBaseService<EF.Entitys.FPayOrder>
    {
    
    }
    public partial interface IFSys_Config:IBaseService<EF.Entitys.FSys_Config>
    {
    
    }
    public partial interface IFSys_Role:IBaseService<EF.Entitys.FSys_Role>
    {
    
    }
    public partial interface IFSysUser:IBaseService<EF.Entitys.FSysUser>
    {
    
    }
    public partial interface IFDataLV:IBaseService<EF.Entitys.FDataLV>
    {
    
    }
    public partial interface IFDataReposInit:IBaseService<EF.Entitys.FDataReposInit>
    {
    
    }
    public partial interface IFDataRepository:IBaseService<EF.Entitys.FDataRepository>
    {
    
    }
    public partial interface IFPayWay:IBaseService<EF.Entitys.FPayWay>
    {
    
    }
    public partial interface IFSys_Category:IBaseService<EF.Entitys.FSys_Category>
    {
    
    }
    public partial interface IFMoments:IBaseService<EF.Entitys.FMoments>
    {
    
    }
    public partial interface IFMomentsReply:IBaseService<EF.Entitys.FMomentsReply>
    {
    
    }
    public partial interface IFAI:IBaseService<EF.Entitys.FAI>
    {
    
    }
    public partial interface IView_AdminUser:IBaseService<EF.Entitys.View_AdminUser>
    {
    
    }
    public partial interface IFSys_LoginSession:IBaseService<EF.Entitys.FSys_LoginSession>
    {
    
    }
    public partial interface IFMenus:IBaseService<EF.Entitys.FMenus>
    {
    
    }
    public partial interface IFSysUser_Invite:IBaseService<EF.Entitys.FSysUser_Invite>
    {
    
    }
    public partial interface ISX_News:IBaseService<EF.Entitys.SX_News>
    {
    
    }
    public partial interface ISX_SiteConfig:IBaseService<EF.Entitys.SX_SiteConfig>
    {
    
    }
    
    
    
}
