//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IService.Sons
{
    using System;
    
    public partial interface IFNews:IBaseService<EF.Entitys.FNews>
    {
    
    }
    public partial interface IFRepository:IBaseService<EF.Entitys.FRepository>
    {
    
    }
    public partial interface IInRawMaterial:IBaseService<EF.Entitys.InRawMaterial>
    {
    
    }
    
    
    
}
