//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IService.Sons
{
    using System;
    
    public partial interface IFNews:IBaseService<EF.Entitys.FNews>
    {
    
    }
    public partial interface IFAI:IBaseService<EF.Entitys.FAI>
    {
    
    }
    public partial interface IFDataMaterial:IBaseService<EF.Entitys.FDataMaterial>
    {
    
    }
    public partial interface IFDataRepository:IBaseService<EF.Entitys.FDataRepository>
    {
    
    }
    public partial interface IFPayGood:IBaseService<EF.Entitys.FPayGood>
    {
    
    }
    public partial interface IFPayMert:IBaseService<EF.Entitys.FPayMert>
    {
    
    }
    public partial interface IFPayOrder:IBaseService<EF.Entitys.FPayOrder>
    {
    
    }
    public partial interface IFSys_Config:IBaseService<EF.Entitys.FSys_Config>
    {
    
    }
    public partial interface IFPayWay:IBaseService<EF.Entitys.FPayWay>
    {
    
    }
    public partial interface IFSys_LoginSession:IBaseService<EF.Entitys.FSys_LoginSession>
    {
    
    }
    public partial interface IFSys_Role:IBaseService<EF.Entitys.FSys_Role>
    {
    
    }
    public partial interface IFSysUser:IBaseService<EF.Entitys.FSysUser>
    {
    
    }
    
    
    
}
