//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAI
    {
        public int ID { get; set; }
        public System.DateTime DT { get; set; }
        public string Cate { get; set; }
        public decimal NPrice { get; set; }
        public string TurnType { get; set; }
        public string DataType { get; set; }
        public bool IsPublish { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> ResultHight { get; set; }
        public Nullable<decimal> ResultLow { get; set; }
        public Nullable<decimal> ResultClose { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<decimal> AValue { get; set; }
        public Nullable<decimal> Star { get; set; }
        public Nullable<decimal> ReviseLV { get; set; }
        public Nullable<decimal> ReviseStar { get; set; }
        public string CateType { get; set; }
        public bool IsAbandon { get; set; }
    }
}
