//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDataMaterial
    {
        public int ID { get; set; }
        public string PName { get; set; }
        public string PCode { get; set; }
        public string PCate { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public decimal RisePrice { get; set; }
        public decimal RiseRange { get; set; }
        public int DateTime { get; set; }
    }
}
