//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDataRepository
    {
        public long ID { get; set; }
        public int Date { get; set; }
        public string CateName { get; set; }
        public string Reps { get; set; }
        public int YTDSum { get; set; }
        public int TDSum { get; set; }
        public int Change { get; set; }
        public System.DateTime DTime { get; set; }
        public int Type { get; set; }
        public string TradeHouse { get; set; }
    }
}
