//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDataReposInit
    {
        public int ID { get; set; }
        public int Date { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
        public int IsCheckFinish { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
