//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FNews
    {
        public int ID { get; set; }
        public string NewsTitle { get; set; }
        public int NewsType { get; set; }
        public int NewsRes { get; set; }
        public string NSource { get; set; }
        public string NewsUrl { get; set; }
        public string NewContent { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDel { get; set; }
        public bool IsPublish { get; set; }
        public string TradeHouse { get; set; }
    }
}
