//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRepository
    {
        public long ID { get; set; }
        public string Exchange { get; set; }
        public string CateName { get; set; }
        public string Reps { get; set; }
        public decimal YTDSum { get; set; }
        public decimal TDSum { get; set; }
        public decimal Change { get; set; }
        public System.DateTime DTime { get; set; }
    }
}
