//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SX_News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string SiteName { get; set; }
    }
}
