//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class SX_SiteConfig
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string SiteListXPath { get; set; }
        public string SiteItemXPath { get; set; }
        public string SiteItemXPath2 { get; set; }
        public string XPathNote1 { get; set; }
        public string XPathNote2 { get; set; }
    }
}
