//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Service.Sons
{
    using System;
    
    public partial class FNews:BaseService<EF.Entitys.FNews>,EF.IService.Sons.IFNews
    {
    	    //IRespository.Sons.IFNews dal;
            public override void Setdal()
            {
                dal = base.DBSession.FNews;
                base.dal = dal;
            }
    }
    public partial class FRepository:BaseService<EF.Entitys.FRepository>,EF.IService.Sons.IFRepository
    {
    	    //IRespository.Sons.IFRepository dal;
            public override void Setdal()
            {
                dal = base.DBSession.FRepository;
                base.dal = dal;
            }
    }
    public partial class InRawMaterial:BaseService<EF.Entitys.InRawMaterial>,EF.IService.Sons.IInRawMaterial
    {
    	    //IRespository.Sons.IInRawMaterial dal;
            public override void Setdal()
            {
                dal = base.DBSession.InRawMaterial;
                base.dal = dal;
            }
    }
    
    
    
}
