//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Service.Sons
{
    using System;
    
    public partial class FDataMaterial:BaseService<EF.Entitys.FDataMaterial>,EF.IService.Sons.IFDataMaterial
    {
    	    //IRespository.Sons.IFDataMaterial dal;
            public override void Setdal()
            {
                dal = base.DBSession.FDataMaterial;
                base.dal = dal;
            }
    }
    public partial class FNews:BaseService<EF.Entitys.FNews>,EF.IService.Sons.IFNews
    {
    	    //IRespository.Sons.IFNews dal;
            public override void Setdal()
            {
                dal = base.DBSession.FNews;
                base.dal = dal;
            }
    }
    public partial class FPayGood:BaseService<EF.Entitys.FPayGood>,EF.IService.Sons.IFPayGood
    {
    	    //IRespository.Sons.IFPayGood dal;
            public override void Setdal()
            {
                dal = base.DBSession.FPayGood;
                base.dal = dal;
            }
    }
    public partial class FPayMert:BaseService<EF.Entitys.FPayMert>,EF.IService.Sons.IFPayMert
    {
    	    //IRespository.Sons.IFPayMert dal;
            public override void Setdal()
            {
                dal = base.DBSession.FPayMert;
                base.dal = dal;
            }
    }
    public partial class FPayOrder:BaseService<EF.Entitys.FPayOrder>,EF.IService.Sons.IFPayOrder
    {
    	    //IRespository.Sons.IFPayOrder dal;
            public override void Setdal()
            {
                dal = base.DBSession.FPayOrder;
                base.dal = dal;
            }
    }
    public partial class FSys_Config:BaseService<EF.Entitys.FSys_Config>,EF.IService.Sons.IFSys_Config
    {
    	    //IRespository.Sons.IFSys_Config dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSys_Config;
                base.dal = dal;
            }
    }
    public partial class FSys_Role:BaseService<EF.Entitys.FSys_Role>,EF.IService.Sons.IFSys_Role
    {
    	    //IRespository.Sons.IFSys_Role dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSys_Role;
                base.dal = dal;
            }
    }
    public partial class FSysUser:BaseService<EF.Entitys.FSysUser>,EF.IService.Sons.IFSysUser
    {
    	    //IRespository.Sons.IFSysUser dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSysUser;
                base.dal = dal;
            }
    }
    public partial class FDataLV:BaseService<EF.Entitys.FDataLV>,EF.IService.Sons.IFDataLV
    {
    	    //IRespository.Sons.IFDataLV dal;
            public override void Setdal()
            {
                dal = base.DBSession.FDataLV;
                base.dal = dal;
            }
    }
    public partial class FDataReposInit:BaseService<EF.Entitys.FDataReposInit>,EF.IService.Sons.IFDataReposInit
    {
    	    //IRespository.Sons.IFDataReposInit dal;
            public override void Setdal()
            {
                dal = base.DBSession.FDataReposInit;
                base.dal = dal;
            }
    }
    public partial class FDataRepository:BaseService<EF.Entitys.FDataRepository>,EF.IService.Sons.IFDataRepository
    {
    	    //IRespository.Sons.IFDataRepository dal;
            public override void Setdal()
            {
                dal = base.DBSession.FDataRepository;
                base.dal = dal;
            }
    }
    public partial class FPayWay:BaseService<EF.Entitys.FPayWay>,EF.IService.Sons.IFPayWay
    {
    	    //IRespository.Sons.IFPayWay dal;
            public override void Setdal()
            {
                dal = base.DBSession.FPayWay;
                base.dal = dal;
            }
    }
    public partial class FSys_Category:BaseService<EF.Entitys.FSys_Category>,EF.IService.Sons.IFSys_Category
    {
    	    //IRespository.Sons.IFSys_Category dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSys_Category;
                base.dal = dal;
            }
    }
    public partial class FMoments:BaseService<EF.Entitys.FMoments>,EF.IService.Sons.IFMoments
    {
    	    //IRespository.Sons.IFMoments dal;
            public override void Setdal()
            {
                dal = base.DBSession.FMoments;
                base.dal = dal;
            }
    }
    public partial class FMomentsReply:BaseService<EF.Entitys.FMomentsReply>,EF.IService.Sons.IFMomentsReply
    {
    	    //IRespository.Sons.IFMomentsReply dal;
            public override void Setdal()
            {
                dal = base.DBSession.FMomentsReply;
                base.dal = dal;
            }
    }
    public partial class FAI:BaseService<EF.Entitys.FAI>,EF.IService.Sons.IFAI
    {
    	    //IRespository.Sons.IFAI dal;
            public override void Setdal()
            {
                dal = base.DBSession.FAI;
                base.dal = dal;
            }
    }
    public partial class View_AdminUser:BaseService<EF.Entitys.View_AdminUser>,EF.IService.Sons.IView_AdminUser
    {
    	    //IRespository.Sons.IView_AdminUser dal;
            public override void Setdal()
            {
                dal = base.DBSession.View_AdminUser;
                base.dal = dal;
            }
    }
    public partial class FSys_LoginSession:BaseService<EF.Entitys.FSys_LoginSession>,EF.IService.Sons.IFSys_LoginSession
    {
    	    //IRespository.Sons.IFSys_LoginSession dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSys_LoginSession;
                base.dal = dal;
            }
    }
    public partial class FMenus:BaseService<EF.Entitys.FMenus>,EF.IService.Sons.IFMenus
    {
    	    //IRespository.Sons.IFMenus dal;
            public override void Setdal()
            {
                dal = base.DBSession.FMenus;
                base.dal = dal;
            }
    }
    public partial class FSysUser_Invite:BaseService<EF.Entitys.FSysUser_Invite>,EF.IService.Sons.IFSysUser_Invite
    {
    	    //IRespository.Sons.IFSysUser_Invite dal;
            public override void Setdal()
            {
                dal = base.DBSession.FSysUser_Invite;
                base.dal = dal;
            }
    }
    public partial class SX_News:BaseService<EF.Entitys.SX_News>,EF.IService.Sons.ISX_News
    {
    	    //IRespository.Sons.ISX_News dal;
            public override void Setdal()
            {
                dal = base.DBSession.SX_News;
                base.dal = dal;
            }
    }
    public partial class SX_SiteConfig:BaseService<EF.Entitys.SX_SiteConfig>,EF.IService.Sons.ISX_SiteConfig
    {
    	    //IRespository.Sons.ISX_SiteConfig dal;
            public override void Setdal()
            {
                dal = base.DBSession.SX_SiteConfig;
                base.dal = dal;
            }
    }
    
    
    
}
