//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class ServiceSession:IService.IServiceSession
    {
    	public IService.Sons.IFNews FNews
    	{
    		get
    		{
    			return new Service.Sons.FNews();
    		}
    	}
    	public IService.Sons.IFRepository FRepository
    	{
    		get
    		{
    			return new Service.Sons.FRepository();
    		}
    	}
    	public IService.Sons.IInRawMaterial InRawMaterial
    	{
    		get
    		{
    			return new Service.Sons.InRawMaterial();
    		}
    	}
    }
    
    
    
}
