//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public partial class ServiceSession:IService.IServiceSession
    {
    	public IService.Sons.IFAI FAI
    	{
    		get
    		{
    			return new Service.Sons.FAI();
    		}
    	}
    	public IService.Sons.IFDataMaterial FDataMaterial
    	{
    		get
    		{
    			return new Service.Sons.FDataMaterial();
    		}
    	}
    	public IService.Sons.IFNews FNews
    	{
    		get
    		{
    			return new Service.Sons.FNews();
    		}
    	}
    	public IService.Sons.IFPayGood FPayGood
    	{
    		get
    		{
    			return new Service.Sons.FPayGood();
    		}
    	}
    	public IService.Sons.IFPayMert FPayMert
    	{
    		get
    		{
    			return new Service.Sons.FPayMert();
    		}
    	}
    	public IService.Sons.IFPayOrder FPayOrder
    	{
    		get
    		{
    			return new Service.Sons.FPayOrder();
    		}
    	}
    	public IService.Sons.IFSys_Config FSys_Config
    	{
    		get
    		{
    			return new Service.Sons.FSys_Config();
    		}
    	}
    	public IService.Sons.IFSys_LoginSession FSys_LoginSession
    	{
    		get
    		{
    			return new Service.Sons.FSys_LoginSession();
    		}
    	}
    	public IService.Sons.IFSys_Role FSys_Role
    	{
    		get
    		{
    			return new Service.Sons.FSys_Role();
    		}
    	}
    	public IService.Sons.IFSysUser FSysUser
    	{
    		get
    		{
    			return new Service.Sons.FSysUser();
    		}
    	}
    	public IService.Sons.IFDataLV FDataLV
    	{
    		get
    		{
    			return new Service.Sons.FDataLV();
    		}
    	}
    	public IService.Sons.IFDataReposInit FDataReposInit
    	{
    		get
    		{
    			return new Service.Sons.FDataReposInit();
    		}
    	}
    	public IService.Sons.IFDataRepository FDataRepository
    	{
    		get
    		{
    			return new Service.Sons.FDataRepository();
    		}
    	}
    	public IService.Sons.IFPayWay FPayWay
    	{
    		get
    		{
    			return new Service.Sons.FPayWay();
    		}
    	}
    }
    
    
    
}
