//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IRespository.Sons
{
    using System;
    
    public partial interface IFDataMaterial:IBaseRespository<EF.Entitys.FDataMaterial>
    {
    
    }
    public partial interface IFNews:IBaseRespository<EF.Entitys.FNews>
    {
    
    }
    public partial interface IFPayGood:IBaseRespository<EF.Entitys.FPayGood>
    {
    
    }
    public partial interface IFPayMert:IBaseRespository<EF.Entitys.FPayMert>
    {
    
    }
    public partial interface IFPayOrder:IBaseRespository<EF.Entitys.FPayOrder>
    {
    
    }
    public partial interface IFSys_Config:IBaseRespository<EF.Entitys.FSys_Config>
    {
    
    }
    public partial interface IFSys_Role:IBaseRespository<EF.Entitys.FSys_Role>
    {
    
    }
    public partial interface IFSysUser:IBaseRespository<EF.Entitys.FSysUser>
    {
    
    }
    public partial interface IFDataLV:IBaseRespository<EF.Entitys.FDataLV>
    {
    
    }
    public partial interface IFDataReposInit:IBaseRespository<EF.Entitys.FDataReposInit>
    {
    
    }
    public partial interface IFDataRepository:IBaseRespository<EF.Entitys.FDataRepository>
    {
    
    }
    public partial interface IFPayWay:IBaseRespository<EF.Entitys.FPayWay>
    {
    
    }
    public partial interface IFSys_Category:IBaseRespository<EF.Entitys.FSys_Category>
    {
    
    }
    public partial interface IFMoments:IBaseRespository<EF.Entitys.FMoments>
    {
    
    }
    public partial interface IFMomentsReply:IBaseRespository<EF.Entitys.FMomentsReply>
    {
    
    }
    public partial interface IFAI:IBaseRespository<EF.Entitys.FAI>
    {
    
    }
    public partial interface IView_AdminUser:IBaseRespository<EF.Entitys.View_AdminUser>
    {
    
    }
    public partial interface IFSys_LoginSession:IBaseRespository<EF.Entitys.FSys_LoginSession>
    {
    
    }
    public partial interface IFMenus:IBaseRespository<EF.Entitys.FMenus>
    {
    
    }
    public partial interface IFSysUser_Invite:IBaseRespository<EF.Entitys.FSysUser_Invite>
    {
    
    }
    public partial interface ISX_News:IBaseRespository<EF.Entitys.SX_News>
    {
    
    }
    public partial interface ISX_SiteConfig:IBaseRespository<EF.Entitys.SX_SiteConfig>
    {
    
    }
    
    
    
}
