//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IRespository.Sons
{
    using System;
    
    public partial interface IFNews:IBaseRespository<EF.Entitys.FNews>
    {
    
    }
    public partial interface IFRepository:IBaseRespository<EF.Entitys.FRepository>
    {
    
    }
    public partial interface IInRawMaterial:IBaseRespository<EF.Entitys.InRawMaterial>
    {
    
    }
    
    
    
}
