//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IRespository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IRespositorySession
    {
    	IRespository.Sons.IFNews FNews{ get; }
    	IRespository.Sons.IFAI FAI{ get; }
    	IRespository.Sons.IFDataMaterial FDataMaterial{ get; }
    	IRespository.Sons.IFDataRepository FDataRepository{ get; }
    	IRespository.Sons.IFPayGood FPayGood{ get; }
    	IRespository.Sons.IFPayMert FPayMert{ get; }
    	IRespository.Sons.IFPayOrder FPayOrder{ get; }
    	IRespository.Sons.IFSys_Config FSys_Config{ get; }
    	IRespository.Sons.IFPayWay FPayWay{ get; }
    	IRespository.Sons.IFSys_LoginSession FSys_LoginSession{ get; }
    	IRespository.Sons.IFSys_Role FSys_Role{ get; }
    	IRespository.Sons.IFSysUser FSysUser{ get; }
    }
    
    
}
