//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IRespository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IRespositorySession
    {
    	IRespository.Sons.IFDataMaterial FDataMaterial{ get; }
    	IRespository.Sons.IFNews FNews{ get; }
    	IRespository.Sons.IFPayGood FPayGood{ get; }
    	IRespository.Sons.IFPayMert FPayMert{ get; }
    	IRespository.Sons.IFPayOrder FPayOrder{ get; }
    	IRespository.Sons.IFSys_Config FSys_Config{ get; }
    	IRespository.Sons.IFSys_Role FSys_Role{ get; }
    	IRespository.Sons.IFSysUser FSysUser{ get; }
    	IRespository.Sons.IFDataLV FDataLV{ get; }
    	IRespository.Sons.IFDataReposInit FDataReposInit{ get; }
    	IRespository.Sons.IFDataRepository FDataRepository{ get; }
    	IRespository.Sons.IFPayWay FPayWay{ get; }
    	IRespository.Sons.IFSys_Category FSys_Category{ get; }
    	IRespository.Sons.IFMoments FMoments{ get; }
    	IRespository.Sons.IFMomentsReply FMomentsReply{ get; }
    	IRespository.Sons.IFAI FAI{ get; }
    	IRespository.Sons.IView_AdminUser View_AdminUser{ get; }
    	IRespository.Sons.IFSys_LoginSession FSys_LoginSession{ get; }
    	IRespository.Sons.IFMenus FMenus{ get; }
    	IRespository.Sons.IFSysUser_Invite FSysUser_Invite{ get; }
    	IRespository.Sons.ISX_News SX_News{ get; }
    	IRespository.Sons.ISX_SiteConfig SX_SiteConfig{ get; }
    }
    
    
}
