//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IRespository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IRespositorySession
    {
    	IRespository.Sons.IFNews FNews{ get; }
    	IRespository.Sons.IFRepository FRepository{ get; }
    	IRespository.Sons.IInRawMaterial InRawMaterial{ get; }
    }
    
    
}
