//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDataLV
    {
        public int ID { get; set; }
        public int LV { get; set; }
        public int CV { get; set; }
        public int LV2 { get; set; }
        public int FX { get; set; }
        public int STATUS { get; set; }
        public int Result { get; set; }
        public string Type { get; set; }
    }
}
