//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPayMert
    {
        public int ID { get; set; }
        public string MerNo { get; set; }
        public string MerName { get; set; }
        public string MerApiUrl { get; set; }
        public string MerApiUrlB { get; set; }
        public string MerApiUrlC { get; set; }
        public string MerEncryKey { get; set; }
        public string MerPrivateKey { get; set; }
        public string MerPublicKey { get; set; }
        public string MerSerPubliKey { get; set; }
        public int IsDel { get; set; }
        public string NoteA { get; set; }
        public string NoteB { get; set; }
    }
}
