//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBindCards
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string IDCardNo { get; set; }
        public string BankCardNo { get; set; }
        public string BankType { get; set; }
        public string Account { get; set; }
        public int VaildState { get; set; }
        public string VaildType { get; set; }
        public int IsAvailable { get; set; }
        public int IsDefault { get; set; }
        public int IsDel { get; set; }
        public int IsSafe { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string Remarks { get; set; }
    }
}
