//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Entitys
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_IPayWayBank
    {
        public int ID { get; set; }
        public string SerNo { get; set; }
        public string PayType { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public string BankValue { get; set; }
        public string OnceLimit { get; set; }
        public string DayLimit { get; set; }
        public string MonthLimit { get; set; }
        public int IsAvailable { get; set; }
        public int OrderNo { get; set; }
        public int IsJumpBank { get; set; }
        public int IsSuptPC { get; set; }
        public int IsSuptWap { get; set; }
        public string Expr1 { get; set; }
        public string PNo { get; set; }
        public string DataType { get; set; }
    }
}
