//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IServiceSession
    {
    	IService.Sons.IFDataMaterial FDataMaterial{ get; }
    	IService.Sons.IFNews FNews{ get; }
    	IService.Sons.IFPayGood FPayGood{ get; }
    	IService.Sons.IFPayMert FPayMert{ get; }
    	IService.Sons.IFPayOrder FPayOrder{ get; }
    	IService.Sons.IFSys_Config FSys_Config{ get; }
    	IService.Sons.IFSys_Role FSys_Role{ get; }
    	IService.Sons.IFSysUser FSysUser{ get; }
    	IService.Sons.IFDataLV FDataLV{ get; }
    	IService.Sons.IFDataReposInit FDataReposInit{ get; }
    	IService.Sons.IFDataRepository FDataRepository{ get; }
    	IService.Sons.IFPayWay FPayWay{ get; }
    	IService.Sons.IFSys_Category FSys_Category{ get; }
    	IService.Sons.IFMoments FMoments{ get; }
    	IService.Sons.IFMomentsReply FMomentsReply{ get; }
    	IService.Sons.IFAI FAI{ get; }
    	IService.Sons.IView_AdminUser View_AdminUser{ get; }
    	IService.Sons.IFSys_LoginSession FSys_LoginSession{ get; }
    	IService.Sons.IFMenus FMenus{ get; }
    	IService.Sons.IFSysUser_Invite FSysUser_Invite{ get; }
    }
    
    
}
