//------------------------------------------------------------------------------
// <auto-generated>
//
//CodeBy DJW
// </auto-generated>
//------------------------------------------------------------------------------
namespace EF.IService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IServiceSession
    {
    	IService.Sons.IFNews FNews{ get; }
    	IService.Sons.IFRepository FRepository{ get; }
    	IService.Sons.IInRawMaterial InRawMaterial{ get; }
    }
    
    
}
