//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF.Respository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EF.Entitys;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FNews> FNews { get; set; }
        public virtual DbSet<FRepository> FRepository { get; set; }
        public virtual DbSet<InRawMaterial> InRawMaterial { get; set; }
    }
}
